# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/joao/Documents/UniStuff/2_1 things/AEDA/FEUP-AEDA-Proj1"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/joao/Documents/UniStuff/2_1 things/AEDA/FEUP-AEDA-Proj1"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/joao/Documents/UniStuff/2_1 things/AEDA/FEUP-AEDA-Proj1/CMakeFiles" "/home/joao/Documents/UniStuff/2_1 things/AEDA/FEUP-AEDA-Proj1/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/joao/Documents/UniStuff/2_1 things/AEDA/FEUP-AEDA-Proj1/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FEUP-AEDA-Proj1

# Build rule for target.
FEUP-AEDA-Proj1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FEUP-AEDA-Proj1
.PHONY : FEUP-AEDA-Proj1

# fast build rule for target.
FEUP-AEDA-Proj1/fast:
	$(MAKE) -f CMakeFiles/FEUP-AEDA-Proj1.dir/build.make CMakeFiles/FEUP-AEDA-Proj1.dir/build
.PHONY : FEUP-AEDA-Proj1/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/FEUP-AEDA-Proj1.dir/build.make CMakeFiles/FEUP-AEDA-Proj1.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/FEUP-AEDA-Proj1.dir/build.make CMakeFiles/FEUP-AEDA-Proj1.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/FEUP-AEDA-Proj1.dir/build.make CMakeFiles/FEUP-AEDA-Proj1.dir/main.cpp.s
.PHONY : main.cpp.s

src/cards.o: src/cards.cpp.o

.PHONY : src/cards.o

# target to build an object file
src/cards.cpp.o:
	$(MAKE) -f CMakeFiles/FEUP-AEDA-Proj1.dir/build.make CMakeFiles/FEUP-AEDA-Proj1.dir/src/cards.cpp.o
.PHONY : src/cards.cpp.o

src/cards.i: src/cards.cpp.i

.PHONY : src/cards.i

# target to preprocess a source file
src/cards.cpp.i:
	$(MAKE) -f CMakeFiles/FEUP-AEDA-Proj1.dir/build.make CMakeFiles/FEUP-AEDA-Proj1.dir/src/cards.cpp.i
.PHONY : src/cards.cpp.i

src/cards.s: src/cards.cpp.s

.PHONY : src/cards.s

# target to generate assembly for a file
src/cards.cpp.s:
	$(MAKE) -f CMakeFiles/FEUP-AEDA-Proj1.dir/build.make CMakeFiles/FEUP-AEDA-Proj1.dir/src/cards.cpp.s
.PHONY : src/cards.cpp.s

src/date.o: src/date.cpp.o

.PHONY : src/date.o

# target to build an object file
src/date.cpp.o:
	$(MAKE) -f CMakeFiles/FEUP-AEDA-Proj1.dir/build.make CMakeFiles/FEUP-AEDA-Proj1.dir/src/date.cpp.o
.PHONY : src/date.cpp.o

src/date.i: src/date.cpp.i

.PHONY : src/date.i

# target to preprocess a source file
src/date.cpp.i:
	$(MAKE) -f CMakeFiles/FEUP-AEDA-Proj1.dir/build.make CMakeFiles/FEUP-AEDA-Proj1.dir/src/date.cpp.i
.PHONY : src/date.cpp.i

src/date.s: src/date.cpp.s

.PHONY : src/date.s

# target to generate assembly for a file
src/date.cpp.s:
	$(MAKE) -f CMakeFiles/FEUP-AEDA-Proj1.dir/build.make CMakeFiles/FEUP-AEDA-Proj1.dir/src/date.cpp.s
.PHONY : src/date.cpp.s

src/utilities.o: src/utilities.cpp.o

.PHONY : src/utilities.o

# target to build an object file
src/utilities.cpp.o:
	$(MAKE) -f CMakeFiles/FEUP-AEDA-Proj1.dir/build.make CMakeFiles/FEUP-AEDA-Proj1.dir/src/utilities.cpp.o
.PHONY : src/utilities.cpp.o

src/utilities.i: src/utilities.cpp.i

.PHONY : src/utilities.i

# target to preprocess a source file
src/utilities.cpp.i:
	$(MAKE) -f CMakeFiles/FEUP-AEDA-Proj1.dir/build.make CMakeFiles/FEUP-AEDA-Proj1.dir/src/utilities.cpp.i
.PHONY : src/utilities.cpp.i

src/utilities.s: src/utilities.cpp.s

.PHONY : src/utilities.s

# target to generate assembly for a file
src/utilities.cpp.s:
	$(MAKE) -f CMakeFiles/FEUP-AEDA-Proj1.dir/build.make CMakeFiles/FEUP-AEDA-Proj1.dir/src/utilities.cpp.s
.PHONY : src/utilities.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... FEUP-AEDA-Proj1"
	@echo "... edit_cache"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/cards.o"
	@echo "... src/cards.i"
	@echo "... src/cards.s"
	@echo "... src/date.o"
	@echo "... src/date.i"
	@echo "... src/date.s"
	@echo "... src/utilities.o"
	@echo "... src/utilities.i"
	@echo "... src/utilities.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

